# override in application-default.properties
baseUrl=http://localhost:8080

vaadin.frontend.hotdeploy=true

server.servlet.session.timeout=4h

spring.jpa.properties.hibernate.default_batch_fetch_size=1024
spring.jpa.generate-ddl=false
# validate the entities vs the database schema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# == liquibase ==
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
#spring.liquibase.secureParsing=false # this is not picked up, moved to main as system property
spring.liquibase.dropFirst=false
spring.liquibase.user=${spring.datasource.username}
spring.liquibase.password=${spring.datasource.password}
